# Generated by Django 3.1.6 on 2021-07-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='hotel',
        ),
    ]
