# Generated by Django 3.1.6 on 2021-07-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210718_2115'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
