# Generated by Django 3.1.6 on 2021-07-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210718_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
