# Generated by Django 3.1.6 on 2021-07-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dis',
            field=models.CharField(max_length=100),
        ),
    ]
