# Generated by Django 3.1.6 on 2021-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_products_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('food', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
